import os
import re
import uuid
import json
import zipfile
import logging
import datetime
import tempfile
import mimetypes
from pathlib import Path
from io import BytesIO
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Union, Tuple, Any

try:
    import markdown
    MARKDOWN_AVAILABLE = True
except ImportError:
    MARKDOWN_AVAILABLE = False


# =============================================================================
# Logging Configuration
# =============================================================================
logger = logging.getLogger("nex.writing.epub_adapter")
logger.setLevel(logging.INFO)
if not logger.handlers:
    ch = logging.StreamHandler()
    ch.setLevel(logging.INFO)
    formatter = logging.Formatter(
        "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    )
    ch.setFormatter(formatter)
    logger.addHandler(ch)


# =============================================================================
# Exceptions
# =============================================================================
class EpubAdapterError(Exception):
    """Base exception for EPUB Adapter errors."""
    pass


class MetadataMissingError(EpubAdapterError):
    """Raised when required metadata is missing."""
    pass


class ChapterProcessingError(EpubAdapterError):
    """Raised when a chapter cannot be processed or converted."""
    pass


class DependencyError(EpubAdapterError):
    """Raised when a required external dependency is missing."""
    pass


# =============================================================================
# Data Models
# =============================================================================
@dataclass
class EpubMetadata:
    """
    Metadata container for the EPUB publication.
    Complies with Dublin Core metadata elements required by EPUB3.
    """
    title: str
    author: str
    language: str = "en"
    identifier: str = field(default_factory=lambda: str(uuid.uuid4()))
    publisher: str = "Nex Autonomous Research Engine"
    description: str = "A comprehensive research report generated by Nex."
    subjects: List[str] = field(default_factory=list)
    publication_date: str = field(
        default_factory=lambda: datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    )
    rights: str = "All rights reserved."
    cover_image_path: Optional[Union[str, Path]] = None
    isbn: Optional[str] = None
    
    def validate(self) -> None:
        """Validates that all required metadata fields are present and correctly formatted."""
        if not self.title:
            raise MetadataMissingError("EPUB title is required.")
        if not self.author:
            raise MetadataMissingError("EPUB author is required.")
        if not self.identifier:
            raise MetadataMissingError("EPUB identifier (UUID/ISBN) is required.")


@dataclass
class EpubChapter:
    """
    Represents a single chapter or section in the EPUB.
    """
    title: str
    content_markdown: str
    order: int
    html_content: str = ""
    file_name: str = ""
    id: str = ""
    is_frontmatter: bool = False

    def __post_init__(self):
        # Generate safe filename and ID if not provided
        safe_title = re.sub(r'[^a-z0-9]+', '_', self.title.lower()).strip('_')
        if not self.id:
            self.id = f"chapter_{self.order:03d}_{safe_title}"
        if not self.file_name:
            self.file_name = f"{self.id}.xhtml"


# =============================================================================
# EPUB Templates (EPUB 3.0 Standard + Kindle KF8 Compatibility)
# =============================================================================

CONTAINER_XML = """<?xml version="1.0" encoding="UTF-8"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
    <rootfiles>
        <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
    </rootfiles>
</container>
"""

CONTENT_OPF_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://www.idpf.org/2007/opf" unique-identifier="pub-id" version="3.0">
    <metadata xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf">
        <dc:title>{title}</dc:title>
        <dc:creator id="creator">{author}</dc:creator>
        <dc:language>{language}</dc:language>
        <dc:identifier id="pub-id">{identifier}</dc:identifier>
        <dc:publisher>{publisher}</dc:publisher>
        <dc:description>{description}</dc:description>
        <dc:date>{date}</dc:date>
        <dc:rights>{rights}</dc:rights>
        <meta property="dcterms:modified">{date}</meta>
        {subjects_xml}
        {cover_meta}
    </metadata>
    <manifest>
        <item id="toc" href="toc.ncx" media-type="application/x-dtbncx+xml"/>
        <item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>
        <item id="style" href="Styles/style.css" media-type="text/css"/>
        {manifest_items}
    </manifest>
    <spine toc="toc">
        {spine_items}
    </spine>
    <guide>
        <reference type="toc" title="Table of Contents" href="nav.xhtml"/>
        {guide_cover}
    </guide>
</package>
"""

TOC_NCX_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">
    <head>
        <meta name="dtb:uid" content="{identifier}"/>
        <meta name="dtb:depth" content="1"/>
        <meta name="dtb:totalPageCount" content="0"/>
        <meta name="dtb:maxPageNumber" content="0"/>
    </head>
    <docTitle>
        <text>{title}</text>
    </docTitle>
    <navMap>
        {nav_points}
    </navMap>
</ncx>
"""

NAV_XHTML_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
<head>
    <title>Table of Contents</title>
    <link rel="stylesheet" type="text/css" href="Styles/style.css"/>
</head>
<body>
    <nav epub:type="toc" id="toc">
        <h1>Table of Contents</h1>
        <ol>
            {nav_items}
        </ol>
    </nav>
</body>
</html>
"""

CHAPTER_XHTML_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
<head>
    <title>{title}</title>
    <link rel="stylesheet" type="text/css" href="../Styles/style.css"/>
</head>
<body>
    <section epub:type="chapter" id="{chapter_id}">
        {content}
    </section>
</body>
</html>
"""

CSS_TEMPLATE = """
/* Nex Standard Research Report EPUB Stylesheet */
/* Optimized for Kindle (KF8) and Apple Books */

body {
    font-family: "Palatino Linotype", "Book Antiqua", Palatino, serif;
    margin: 5%;
    text-align: justify;
    line-height: 1.4;
    color: #333333;
}

h1, h2, h3, h4, h5, h6 {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    color: #111111;
    margin-top: 1.5em;
    margin-bottom: 0.5em;
    page-break-after: avoid;
}

h1 {
    font-size: 2em;
    text-align: left;
    border-bottom: 2px solid #555;
    padding-bottom: 0.2em;
}

h2 {
    font-size: 1.5em;
}

h3 {
    font-size: 1.25em;
}

p {
    text-indent: 1.5em;
    margin-top: 0;
    margin-bottom: 0;
}

/* Don't indent first paragraph after a heading */
h1 + p, h2 + p, h3 + p, h4 + p, h5 + p, h6 + p {
    text-indent: 0;
    margin-top: 0.5em;
}

/* Blockquotes for citations/excerpts */
blockquote {
    margin: 1em 2em;
    padding-left: 1em;
    border-left: 3px solid #888;
    font-style: italic;
    color: #555;
}

blockquote p {
    text-indent: 0;
    margin-bottom: 0.5em;
}

/* Lists */
ul, ol {
    margin-top: 0.5em;
    margin-bottom: 0.5em;
    padding-left: 2em;
}

li {
    margin-bottom: 0.2em;
}

li p {
    text-indent: 0;
}

/* Tables for data presentation */
table {
    width: 100%;
    border-collapse: collapse;
    margin: 1em 0;
    page-break-inside: avoid;
}

th, td {
    border: 1px solid #aaa;
    padding: 0.5em;
    text-align: left;
}

th {
    background-color: #f4f4f4;
    font-weight: bold;
}

/* Code blocks if any technical data is present */
pre {
    background-color: #f8f8f8;
    border: 1px solid #ddd;
    padding: 1em;
    overflow-x: auto;
    font-family: "Courier New", Courier, monospace;
    font-size: 0.9em;
}

code {
    font-family: "Courier New", Courier, monospace;
    background-color: #f8f8f8;
    padding: 0.1em 0.3em;
    border-radius: 3px;
}

/* Images */
img {
    max-width: 100%;
    height: auto;
    display: block;
    margin: 1em auto;
}

/* Links */
a {
    color: #005599;
    text-decoration: none;
}

a:hover {
    text-decoration: underline;
}

/* Frontmatter specific */
.title-page {
    text-align: center;
    margin-top: 20vh;
}

.title-page h1 {
    border: none;
    text-align: center;
    font-size: 2.5em;
}

.title-page .author {
    font-size: 1.2em;
    font-style: italic;
    margin-top: 2em;
}
"""


# =============================================================================
# Core EPUB Builder
# =============================================================================
class EpubBuilder:
    """
    Constructs an EPUB3 file from metadata and chapters.
    Ensures Kindle (KF8) compatibility by generating both EPUB3 nav and EPUB2 NCX.
    """

    def __init__(self, metadata: EpubMetadata):
        self.metadata = metadata
        self.metadata.validate()
        self.chapters: List[EpubChapter] = []
        self.images: Dict[str, bytes] = {}  # filename -> bytes
        self._manifest_items: List[str] = []
        self._spine_items: List[str] = []
        
        if not MARKDOWN_AVAILABLE:
            logger.warning(
                "The 'markdown' package is not installed. "
                "Markdown conversion will use a rudimentary fallback. "
                "Please run `pip install markdown` for production use."
            )

    def add_chapter(self, title: str, markdown_content: str, order: Optional[int] = None, is_frontmatter: bool = False) -> EpubChapter:
        """
        Parses markdown content, converts to XHTML, and adds it to the EPUB structure.
        """
        if order is None:
            order = len(self.chapters) + 1

        html_content = self._convert_markdown_to_html(markdown_content)
        
        # Wrap in XHTML template
        chapter = EpubChapter(
            title=title,
            content_markdown=markdown_content,
            order=order,
            is_frontmatter=is_frontmatter
        )
        
        xhtml = CHAPTER_XHTML_TEMPLATE.format(
            title=self._escape_xml(chapter.title),
            chapter_id=chapter.id,
            content=html_content
        )
        chapter.html_content = xhtml
        
        self.chapters.append(chapter)
        logger.debug(f"Added chapter: {title} (Order: {order})")
        return chapter

    def add_image(self, file_path: Union[str, Path], filename_in_epub: Optional[str] = None) -> str:
        """
        Adds an image to the EPUB archive.
        Returns the internal path (e.g., 'Images/pic.jpg').
        """
        path = Path(file_path)
        if not path.exists():
            raise FileNotFoundError(f"Image not found: {file_path}")
            
        if not filename_in_epub:
            filename_in_epub = path.name
            
        with open(path, 'rb') as f:
            self.images[filename_in_epub] = f.read()
            
        logger.debug(f"Added image: {filename_in_epub}")
        return f"Images/{filename_in_epub}"

    def set_cover(self, file_path: Union[str, Path]) -> None:
        """Sets the cover image for the EPUB."""
        self.metadata.cover_image_path = Path(file_path)

    def _convert_markdown_to_html(self, text: str) -> str:
        """
        Converts Markdown to strict XHTML compliant with EPUB standards.
        Uses the 'markdown' library if available, otherwise falls back to a basic parser.
        """
        if MARKDOWN_AVAILABLE:
            # Use extensions common in research reports
            extensions = [
                'extra',       # tables, footnotes, def lists, etc.
                'sane_lists',  # better list handling
                'toc',         # generate anchor tags
                'nl2br'        # newlines to <br>
            ]
            html = markdown.markdown(text, extensions=extensions)
            # Ensure empty tags are closed properly for strict XML/XHTML
            html = re.sub(r'<br>', '<br/>', html)
            html = re.sub(r'<hr>', '<hr/>', html)
            html = re.sub(r'<img([^>]+)(?<!/)>', r'<img\1/>', html)
            return html
        else:
            return self._fallback_markdown_parser(text)

    def _fallback_markdown_parser(self, text: str) -> str:
        """
        A highly rudimentary fallback parser if the markdown package is missing.
        DO NOT use this in production for complex research reports.
        """
        html_lines = []
        for line in text.split('\n'):
            line = line.strip()
            if not line:
                continue
            if line.startswith('# '):
                html_lines.append(f"<h1>{self._escape_xml(line[2:])}</h1>")
            elif line.startswith('## '):
                html_lines.append(f"<h2>{self._escape_xml(line[3:])}</h2>")
            elif line.startswith('### '):
                html_lines.append(f"<h3>{self._escape_xml(line[4:])}</h3>")
            elif line.startswith('- '):
                html_lines.append(f"<ul><li>{self._escape_xml(line[2:])}</li></ul>")
            else:
                # Basic bold/italic
                line = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', line)
                line = re.sub(r'\*(.*?)\*', r'<em>\1</em>', line)
                html_lines.append(f"<p>{self._escape_xml(line)}</p>")
        
        # Cleanup adjacent lists
        joined = "\n".join(html_lines)
        joined = joined.replace("</ul>\n<ul>", "\n")
        return joined

    def _escape_xml(self, text: str) -> str:
        """Escapes characters for XML/XHTML compliance."""
        text = str(text)
        text = text.replace("&", "&amp;")
        text = text.replace("<", "&lt;")
        text = text.replace(">", "&gt;")
        text = text.replace('"', "&quot;")
        text = text.replace("'", "&apos;")
        return text

    def _build_manifest_and_spine(self) -> Tuple[str, str, str, str]:
        """
        Builds the XML strings for the manifest, spine, NCX nav points, and XHTML nav items.
        """
        # Sort chapters by order
        self.chapters.sort(key=lambda c: c.order)
        
        manifest = []
        spine = []
        ncx_nav = []
        xhtml_nav = []
        
        # Add Cover Image to manifest if exists
        cover_meta = ""
        guide_cover = ""
        if self.metadata.cover_image_path:
            cover_path = Path(self.metadata.cover_image_path)
            cover_ext = cover_path.suffix.lower()
            mime_type = "image/jpeg" if cover_ext in ['.jpg', '.jpeg'] else "image/png"
            
            # Read cover image
            with open(cover_path, 'rb') as f:
                self.images['cover' + cover_ext] = f.read()
                
            manifest.append(f'<item id="cover-image" href="Images/cover{cover_ext}" media-type="{mime_type}" properties="cover-image"/>')
            cover_meta = '<meta name="cover" content="cover-image"/>'
            
            # Create a cover.xhtml
            cover_xhtml = f"""<?xml version="1.0" encoding="UTF-8"?>
            <html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
            <head><title>Cover</title><style type="text/css">body {{ margin: 0; padding: 0; text-align: center; }} img {{ max-width: 100%; height: auto; }}</style></head>
            <body><img src="Images/cover{cover_ext}" alt="Cover"/></body>
            </html>"""
            
            self.images['cover.xhtml'] = cover_xhtml.encode('utf-8')
            manifest.append('<item id="cover-xhtml" href="Text/cover.xhtml" media-type="application/xhtml+xml"/>')
            spine.append('<itemref idref="cover-xhtml" linear="yes"/>')
            guide_cover = '<reference type="cover" title="Cover" href="Text/cover.xhtml"/>'

        # Add Chapters
        for i, chapter in enumerate(self.chapters, 1):
            manifest.append(f'<item id="{chapter.id}" href="Text/{chapter.file_name}" media-type="application/xhtml+xml"/>')
            spine.append(f'<itemref idref="{chapter.id}" linear="yes"/>')
            
            # NCX Nav Point (EPUB 2)
            ncx_nav.append(f"""
            <navPoint id="navPoint-{i}" playOrder="{i}">
                <navLabel><text>{self._escape_xml(chapter.title)}</text></navLabel>
                <content src="Text/{chapter.file_name}"/>
            </navPoint>""")
            
            # XHTML Nav Item (EPUB 3)
            xhtml_nav.append(f'<li><a href="Text/{chapter.file_name}">{self._escape_xml(chapter.title)}</a></li>')

        # Add arbitrary images to manifest
        for img_name in self.images.keys():
            if img_name.startswith('cover'): continue # handled above
            if img_name.endswith('.xhtml'): continue
            
            mime_type, _ = mimetypes.guess_type(img_name)
            if not mime_type:
                mime_type = "application/octet-stream"
            img_id = re.sub(r'[^a-zA-Z0-9]', '_', img_name)
            manifest.append(f'<item id="img_{img_id}" href="Images/{img_name}" media-type="{mime_type}"/>')

        return (
            "\n        ".join(manifest),
            "\n        ".join(spine),
            "\n        ".join(ncx_nav),
            "\n            ".join(xhtml_nav),
            cover_meta,
            guide_cover
        )

    def build_to_buffer(self) -> BytesIO:
        """
        Compiles the EPUB into an in-memory BytesIO buffer.
        """
        logger.info(f"Building EPUB: {self.metadata.title}")
        buffer = BytesIO()
        
        # EPUB requires specific ZIP formatting (mimetype must be first, uncompressed)
        with zipfile.ZipFile(buffer, 'w') as epub_zip:
            # 1. mimetype
            epub_zip.writestr('mimetype', 'application/epub+zip', compress_type=zipfile.ZIP_STORED)
            
            # 2. META-INF/container.xml
            epub_zip.writestr('META-INF/container.xml', CONTAINER_XML, compress_type=zipfile.ZIP_DEFLATED)
            
            # 3. Compile dynamic contents
            manifest_items, spine_items, ncx_nav, xhtml_nav, cover_meta, guide_cover = self._build_manifest_and_spine()
            
            # Subjects metadata
            subjects_xml = "\n        ".join([f"<dc:subject>{self._escape_xml(s)}</dc:subject>" for s in self.metadata.subjects])
            
            # OEBPS/content.opf
            content_opf = CONTENT_OPF_TEMPLATE.format(
                title=self._escape_xml(self.metadata.title),
                author=self._escape_xml(self.metadata.author),
                language=self.metadata.language,
                identifier=self._escape_xml(self.metadata.identifier),
                publisher=self._escape_xml(self.metadata.publisher),
                description=self._escape_xml(self.metadata.description),
                date=self.metadata.publication_date,
                rights=self._escape_xml(self.metadata.rights),
                subjects_xml=subjects_xml,
                cover_meta=cover_meta,
                manifest_items=manifest_items,
                spine_items=spine_items,
                guide_cover=guide_cover
            )
            epub_zip.writestr('OEBPS/content.opf', content_opf, compress_type=zipfile.ZIP_DEFLATED)
            
            # OEBPS/toc.ncx
            toc_ncx = TOC_NCX_TEMPLATE.format(
                identifier=self._escape_xml(self.metadata.identifier),
                title=self._escape_xml(self.metadata.title),
                nav_points=ncx_nav
            )
            epub_zip.writestr('OEBPS/toc.ncx', toc_ncx, compress_type=zipfile.ZIP_DEFLATED)
            
            # OEBPS/nav.xhtml
            nav_xhtml = NAV_XHTML_TEMPLATE.format(nav_items=xhtml_nav)
            epub_zip.writestr('OEBPS/nav.xhtml', nav_xhtml, compress_type=zipfile.ZIP_DEFLATED)
            
            # OEBPS/Styles/style.css
            epub_zip.writestr('OEBPS/Styles/style.css', CSS_TEMPLATE, compress_type=zipfile.ZIP_DEFLATED)
            
            # Write Chapters
            for chapter in self.chapters:
                epub_zip.writestr(f'OEBPS/Text/{chapter.file_name}', chapter.html_content, compress_type=zipfile.ZIP_DEFLATED)
                
            # Write Images & Cover XHTML
            for img_name, img_data in self.images.items():
                if img_name.endswith('.xhtml'):
                    epub_zip.writestr(f'OEBPS/Text/{img_name}', img_data, compress_type=zipfile.ZIP_DEFLATED)
                else:
                    epub_zip.writestr(f'OEBPS/Images/{img_name}', img_data, compress_type=zipfile.ZIP_DEFLATED)

        buffer.seek(0)
        logger.info("EPUB build complete.")
        return buffer

    def build_to_file(self, output_path: Union[str, Path]) -> None:
        """
        Compiles the EPUB and writes it directly to the filesystem.
        """
        buffer = self.build_to_buffer()
        path = Path(output_path)
        
        # Ensure parent directories exist
        path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(path, 'wb') as f:
            f.write(buffer.read())
            
        logger.info(f"EPUB successfully saved to: {path.absolute()}")


# =============================================================================
# Nex Specific Adapter
# =============================================================================
class NexReportEpubAdapter:
    """
    Adapter designed specifically for the Nex Autonomous Research Engine.
    Converts Nex's structured research reports (JSON/Dict) into production-ready EPUBs.
    """

    def __init__(self, report_data: Dict[str, Any]):
        """
        Initializes the adapter with Nex report data.
        Expected schema roughly maps to:
        {
            "metadata": {
                "query": "The original research question",
                "author": "Nex Agent",
                "date": "2023-10-25",
                "tags": ["AI", "Research"]
            },
            "executive_summary": "Markdown text...",
            "sections": [
                {"title": "Introduction", "content": "Markdown text..."},
                {"title": "Methodology", "content": "Markdown text..."}
            ],
            "knowledge_graph_summary": "Markdown text...",
            "references": [
                {"id": 1, "url": "...", "title": "...", "snippet": "..."}
            ]
        }
        """
        self.report_data = report_data
        self._validate_report_data()

    def _validate_report_data(self) -> None:
        """Ensures the injected data conforms to expected Nex structures."""
        if not isinstance(self.report_data, dict):
            raise ValueError("Report data must be a dictionary.")
        if "metadata" not in self.report_data:
            logger.warning("No 'metadata' found in report. Using defaults.")
        if "sections" not in self.report_data:
            raise ValueError("Report data must contain a 'sections' list.")

    def _extract_metadata(self) -> EpubMetadata:
        """Maps Nex report metadata to EPUB metadata."""
        meta_node = self.report_data.get("metadata", {})
        
        title = meta_node.get("title", meta_node.get("query", "Nex Autonomous Research Report"))
        author = meta_node.get("author", "Nex Deep Research Engine")
        description = meta_node.get("summary", f"An autonomous deep research report investigating: {title}")
        subjects = meta_node.get("tags", ["Research", "Autonomous Synthesis"])
        
        return EpubMetadata(
            title=title,
            author=author,
            description=description,
            subjects=subjects,
            publisher="Nex Systems"
        )

    def _format_references(self) -> str:
        """Converts the structured references into a Markdown bibliography."""
        refs = self.report_data.get("references", [])
        if not refs:
            return ""
            
        md = ["## Bibliography & Verified Sources\n"]
        md.append("This research report was synthesized by autonomously querying, extracting, and verifying the following open-access sources.\n")
        
        for ref in refs:
            ref_id = ref.get("id", "*")
            title = ref.get("title", "Untitled Source")
            url = ref.get("url", "#")
            snippet = ref.get("snippet", "")
            
            md.append(f"### [{ref_id}] {title}")
            md.append(f"**Source**: [{url}]({url})")
            if snippet:
                md.append(f"> {snippet}")
            md.append("\n---\n")
            
        return "\n".join(md)

    def generate_epub(self, output_path: Union[str, Path], cover_image_path: Optional[str] = None) -> None:
        """
        Orchestrates the conversion from Nex structured data to a final EPUB file.
        """
        metadata = self._extract_metadata()
        if cover_image_path:
            metadata.cover_image_path = Path(cover_image_path)
            
        builder = EpubBuilder(metadata)
        
        order_counter = 1
        
        # 1. Title Page (Auto-generated)
        title_page_md = f"""
<div class="title-page">
<h1>{metadata.title}</h1>
<p class="author">Synthesized by {metadata.author}</p>
<p>Generated on: {datetime.datetime.now().strftime('%Y-%m-%d')}</p>
</div>
"""
        builder.add_chapter("Title Page", title_page_md, order=order_counter, is_frontmatter=True)
        order_counter += 1

        # 2. Executive Summary
        exec_summary = self.report_data.get("executive_summary")
        if exec_summary:
            builder.add_chapter("Executive Summary", f"# Executive Summary\n\n{exec_summary}", order=order_counter)
            order_counter += 1

        # 3. Main Sections
        for section in self.report_data.get("sections", []):
            title = section.get("title", f"Section {order_counter}")
            content = section.get("content", "")
            
            # Ensure the content has a top-level header if missing
            if not content.strip().startswith('#'):
                content = f"# {title}\n\n{content}"
                
            builder.add_chapter(title, content, order=order_counter)
            order_counter += 1

        # 4. Knowledge Graph Synthesis (Optional)
        kg_summary = self.report_data.get("knowledge_graph_summary")
        if kg_summary:
            builder.add_chapter("Knowledge Graph Synthesis", f"# Knowledge Graph Synthesis\n\n{kg_summary}", order=order_counter)
            order_counter += 1

        # 5. References / Bibliography
        references_md = self._format_references()
        if references_md:
            builder.add_chapter("References", references_md, order=order_counter)

        # Build and export
        builder.build_to_file(output_path)


# =============================================================================
# Direct Execution / Testing block
# =============================================================================
if __name__ == "__main__":
    # Example usage demonstrating the pipeline
    logging.basicConfig(level=logging.DEBUG)
    
    sample_nex_report = {
        "metadata": {
            "query": "The impact of quantum computing on cryptographic security protocols by 2030.",
            "author": "Nex Agent Alpha",
            "tags": ["Quantum Computing", "Cryptography", "Cybersecurity"]
        },
        "executive_summary": "Quantum computing poses a significant theoretical threat to RSA and ECC cryptographic standards. This report synthesizes current timelines...",
        "sections": [
            {
                "title": "Introduction to Shor's Algorithm",
                "content": "Shor's algorithm, formulated in 1994, proves that a quantum computer with sufficient logical qubits can factor large prime numbers exponentially faster than classical algorithms.\n\n* Impact on RSA\n* Impact on Elliptic Curve Cryptography"
            },
            {
                "title": "Post-Quantum Cryptography (PQC) Standardization",
                "content": "NIST has initiated a process to standardize PQC algorithms. Latticed-based cryptography is currently the leading candidate.\n\n### Key Candidates\n1. CRYSTALS-Kyber\n2. CRYSTALS-Dilithium\n3. SPHINCS+"
            }
        ],
        "references": [
            {
                "id": 1,
                "title": "NIST Post-Quantum Cryptography Standardization",
                "url": "https://csrc.nist.gov/projects/post-quantum-cryptography",
                "snippet": "The National Institute of Standards and Technology (NIST) is soliciting, evaluating, and standardizing one or more quantum-resistant public-key cryptographic algorithms."
            }
        ]
    }
    
    with tempfile.TemporaryDirectory() as tmpdir:
        output_file = Path(tmpdir) / "nex_quantum_report.epub"
        
        # Instantiate the adapter
        adapter = NexReportEpubAdapter(sample_nex_report)
        
        # Generate the EPUB
        adapter.generate_epub(output_file)
        
        logger.info(f"Test complete. Output size: {output_file.stat().st_size} bytes.")