VALID_TRANSITIONS={'QUEUED':{'LEASED','CANCEL_REQUESTED'},'LEASED':{'RUNNING','QUEUED'},'RUNNING':{'WAITING_RETRY','WAITING_REVIEW','COMPLETED','FAILED','CANCELLED'},'WAITING_RETRY':{'LEASED','FAILED'},'WAITING_REVIEW':{'RUNNING','CANCELLED'},'CANCEL_REQUESTED':{'CANCELLED'},'RECOVERY_REQUIRED':{'QUEUED','FAILED'}}
def transition(state, nxt):
    if nxt not in VALID_TRANSITIONS.get(state,set()): raise ValueError(f'invalid transition {state}->{nxt}')
    return nxt
